### ISSUE TITLE
Tracking Issue for Early Medic Signup

### ISSUE THREAD

**Issue by dibbydoda** [Oldcustard/BakesBot#8]
Just leaving my thoughts here about how early signup for medic should be implemented automatically. I might start working on these in a separate branch and do each as it's own PR if I get time.

- [ ] Bot needs to know which players played medic in a pug. (maybe admin's should be asked by the bot in case there were last minute swaps or drop outs that were dealt with externally)
- [ ] These people are given a discord role with access to an early signup channel.
- [ ] After 3 Pugs, these people are removed from the channel, unless they play medic again in this time, in which case their 3 pugs should reset.
- [ ] Bot needs to announce early by some fixed time in the Medic channel. (Can the bot handle having two spearate signup messages in different channels for the same pug?)

If we go this route we also need to make sure there are no issues if a player first reacts in the Medic channel and then reacts to the same pug in the public channel or vice versa, but I think keeping Medic signups in a separate channel is much neater as you don't have to only allow some people but not others to react to an early signup message, as only Medics have access to it.
